name = "OTF"
version = "0.1.0"
license = "MIT"
author = "Renato Zimmermann"
maintainer = "renato.zimmermann@mail.utoronto.ca"
copyright = "Copyright 2021, Renato Zimmermann"

[library]
source-dir="src"

[[test]]
name="tiny-test"
source-dir="test"
main="tiny_test.f90"

[[test]]
name="min-point-tests"
source-dir="test"
main="min_point_tests.f90"

[test.dependencies]
cafut = { git = "https://github.com/renatomatz/cafut.git" }

[[test]]
name="viz-tests"
source-dir="test"
main="viz_tests.f90"

[test.dependencies]
ogpf = { git = "https://github.com/kookma/ogpf.git" }
sobseq = { git = "https://github.com/renatomatz/sobseq.git" }
